/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.HoaDonChiTietDao;
import dao.HoaDonDao;
import dao.KhachHangDao;
import entity.HoaDon;
import entity.HoaDonChiTiet;
import entity.KhachHang;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Ngoc
 */
public class TheoDoiDonHangPL extends javax.swing.JPanel {
    private HoaDonDao hoaDonRepo = new HoaDonDao();
    private HoaDonChiTietDao chiTietRepo = new HoaDonChiTietDao();
    private KhachHangDao khRepo = new KhachHangDao();
    private DefaultTableModel modelHoaDon;
    private DefaultTableModel modelChiTiet;
    private List<String> hoaDonIds = new ArrayList<>();
    /**
     * Creates new form TheoDoiDonHangPL
     */
    public TheoDoiDonHangPL() {
        initComponents();
        initTable();
    }
      private void initTable() {
        modelHoaDon = (DefaultTableModel) btlHoaDon.getModel();
        modelChiTiet = (DefaultTableModel) btlChiTiet.getModel();
    }

    private void loadHoaDon(int idKH) {
        try {
            List<HoaDon> list = hoaDonRepo.getAll(); // Simplified - get all
            modelHoaDon.setRowCount(0);
            hoaDonIds.clear();
            for (HoaDon hd : list) {
                modelHoaDon.addRow(new Object[]{
                        hd.getMaHoaDon(),
                        hd.getNgayTao(),
                        hd.getTrangThaiDonHang(),
                        String.format("%.0f VND", hd.getTongTien())
                });
                hoaDonIds.add(hd.getMaHoaDon());
            }
            if (list.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không có đơn hàng nào!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tải đơn hàng: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void loadChiTiet(String maHoaDon) {
        try {
            List<HoaDonChiTiet> list = chiTietRepo.findById(maHoaDon);
            modelChiTiet.setRowCount(0);
            
            if (list.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Hóa đơn chưa có chi tiết sản phẩm!");
                return;
            }
            
            for (HoaDonChiTiet ct : list) {
                modelChiTiet.addRow(new Object[]{
                        ct.getMaSanPham() != null ? ct.getMaSanPham() : "N/A",
                        ct.getSoLuong(),
                        String.format("%,.0f VND", ct.getDonGia())
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tải chi tiết: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        btlHoaDon = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        btlChiTiet = new javax.swing.JTable();
        btnDong = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("THEO DÕI ĐƠN HÀNG");

        btlHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã HD", "Ngày tạo", "Trạng thái", "Tổng tiền"
            }
        ));
        btlHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(btlHoaDon);

        btlChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên xe", "Số lượng", "Đơn giá"
            }
        ));
        btlChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlChiTietMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(btlChiTiet);

        btnDong.setText("ĐÓNG");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("BẢNG HÓA ĐƠN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("CHI TIẾT ĐƠN HÀNG");

        jLabel4.setText("Nhập Email:");

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDong)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimKiem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jLabel1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDong)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btlChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlChiTietMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btlChiTietMouseClicked

    private void btlHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlHoaDonMouseClicked
        int index = btlHoaDon.getSelectedRow();
        if (index < 0) return;

        Object value = btlHoaDon.getValueAt(index, 0);
        if (value == null) return;

        try {
            String maHoaDon = value.toString();
            loadChiTiet(maHoaDon);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tải chi tiết: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btlHoaDonMouseClicked

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String email = txtEmail.getText().trim();
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập email!");
            return;
        }

        KhachHang kh = khRepo.findByEmail(email);
        if (kh == null) {
            JOptionPane.showMessageDialog(this, 
                "Email không tồn tại trong hệ thống!\n\n" +
                "Email mẫu để test:\n" +
                "- nva@email.com\n" +
                "- ttb@email.com\n" +
                "- lvc@email.com\n\n" +
                "Hoặc đăng ký tài khoản mới.");
            return;
        }

        loadHoaDon(kh.getId());
    }//GEN-LAST:event_btnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable btlChiTiet;
    private javax.swing.JTable btlHoaDon;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
